language: node_js

node_js:
    - "node"
    - "12"
    - "10"

sudo: false

git:
    submodules: false

# env:
    # - JWT_SECRET="randomSecretJustToRunSomeTests"

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
